PACKAGE_NAME="rpusbdisp"
PACKAGE_VERSION="0.2.1"
BUILT_MODULE_NAME[0]="rp_usbdisplay"
BUILT_MODULE_LOCATION[0]="drivers/linux-driver"
DEST_MODULE_LOCATION[0]="/extra"
MAKE[0]="make -C drivers/linux-driver KERNEL_SOURCE_DIR=${kernel_source_dir} modules"
CLEAN="make -C drivers/linux-driver KERNEL_SOURCE_DIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
